### ISSUE TITLE
js_of_ocaml version?

### ISSUE THREAD

**Issue by psteckler** [ocamllabs/ocaml-integers#29]
Is there a version of `ocaml-integers` which can be used with `js_of_ocaml`?

For the `zarith` library, which depends on C, Jane Street has `zarith_stubs_js`, which removes that dependency.

Is there something like that for this library?

**Comment by yallop** [comment]
There's nothing like that at present, but a contribution of `js_of_ocaml` support would be welcome.

**Comment by psteckler** [comment]
@yallop We'll be working on that, and we hope to upstream it when ready.

**Comment by dannywillems** [comment]
I am also interested in. Any news about it @yallop?

**Comment by psteckler** [comment]
We have something at https://github.com/CodaProtocol/coda/tree/develop/src/lib/integers_stubs_js.

Not yet upstreamed, regrettably.

**Comment by dannywillems** [comment]
I have packaged it locally, and I tested it in my project (quite stupidly, with a simple UInt64 to test the max value). I can publish it. Which licence and which author can I use for the runtime.js file? Can I use MIT?

**Comment by psteckler** [comment]
In fact, we're going to create a repo at https://github.com/o1-labs/. It should be available soon.

**Comment by mrmr1993** [comment]
@dannywillems repo is up https://github.com/o1-labs/integers_stubs_js

**Comment by mrmr1993** [comment]
Suggest leaving this open until ocaml/opam-repository#17110 is merged. Will update here once the package lands in opam.

**Comment by mrmr1993** [comment]
Package is now available in opam. This can be closed.

**Comment by yallop** [comment]
Great!  Is it worth adding a link to the `README` of this library (and perhaps some instructions about how to use the JavaScript stubs together with the code here)?

**Comment by mrmr1993** [comment]
Sounds like a good idea, yes. To use them with dune, it should be as simple as adding the `integers_stubs_js` library to the `libraries` field, usually on the toplevel javascript executable. For example
```dune
(executable
 (name my_js_app)
 (modes js)
 (js_of_ocaml (flags +toplevel.js +dynlink.js))
 (libraries ... integers_stubs_js)
 (preprocess (pps js_of_ocaml-ppx)))
```

**Comment by yallop** [comment]
Thanks.  #31 adds a link to the `js_of_ocaml` stubs to this repository.

It'd be useful to have the build instructions in the `integers_stubs_js` repository, I think.
