### ISSUE TITLE
Missing conversion functions documentation

### ISSUE THREAD

**Issue by raphael-proust** [ocamllabs/ocaml-integers#33]
The documentation for the functions `UInt32.{of,to}_int32` and `UInt64.{of,to}_int64`, is missing.

From reading the macro-heavy C code, I understand that the bit pattern is just copied as-is. Is this correct? Should this be documented more precisely?

**Comment by yallop** [comment]
It'd be good to have these documented.

The functions inherit their semantics from C, where the conversions are defined in terms of values, not bit patterns (even if the effect is the same on many systems):

> When a value with integer type is converted to another integer type other than _Bool, if the value can be represented by the new type, it is unchanged.
> Otherwise, if the new type is unsigned, the value is converted by repeatedly adding or subtracting one more than the maximum value that can be represented in the new type until the value is in the range of the new type.

(So, for example, `Uint32.of_int32 (-1l)` is equal to `-1 + 0xffffffff + 1`.)

**Comment by raphael-proust** [comment]
I will make an MR to add documentation.

**Comment by raphael-proust** [comment]
I was checking the rest of this spec. In the case of unsigned→signed conversions (e.g., `UInt32.to_int32`) the spec says

> Otherwise, the new type is signed and the value cannot be represented in it; either the result is implementation-defined or an implementation-defined signal is raised.

Does this mean this function might act differently on binaries linked against different libraries? Can it raise exceptions in some of them?

And more importantly, is it something that matters to the library?

**Comment by yallop** [comment]
Thanks for looking into this.  It means that the function might act differently when compiled with different compilers (but the compilers have to document what the behaviour is).  We could either 
(a) say that the result is implementation defined (and depends on the C compiler used)
(b) change the implementation so that it's not implementation defined

I think (a) should be easier, but I'm happy with either (a) or (b).

**Comment by raphael-proust** [comment]
I think (a) should be easier, but maybe not as useful for users.

In our project we would prefer (b) because it would avoid multiple machines disagreeing on what shared data means. (Even if that's unlikely in practice.)

There's also a third option: to make the conversions partial with `option`. I don't think it fits in the scope of this library (e.g., use in ctypes) or maybe just as a stricter variant. E.g., something along the lines of `{of,to}_fitting_…`. Or maybe some functions to test whether the value fits (currently requires a bit of a setup from the user) would be welcome?

My current plan (over the next week) is to
- fix the semantic by making bit twiddling functions for the platform-dependent parts (that's not my area of expertise so I'll probably make somewhat inefficient code that might need some tweaking)
- provide tests and documentation for those functions
In addition, if the following are of interest, I can contribute those too:
- provide `YY.fits_into_XX` for each pair YY/XX that has conversion functions
- provide hex pretty-printing (to mimic `"%x"`) and string conversion

**Comment by yallop** [comment]
> fix the semantic by making bit twiddling functions for the platform-dependent parts (that's not my area of expertise so I'll probably make somewhat inefficient code that might need some tweaking)

Thanks.  This sounds good.  Somewhat inefficient is fine; we can always improve the performance later, if necessary.

> provide tests and documentation for those functions

This would be very welcome

> provide YY.fits_into_XX for each pair YY/XX that has conversion functions

I'd prefer to leave this one out of the library for the moment.

> provide hex pretty-printing (to mimic "%x") and string conversion

This one would be useful, though.

**Comment by raphael-proust** [comment]
The MR is now ready, let's take all the discussion there.
